### PR TITLE
Include note about the git access token

### PR DESCRIPTION
**Pull request by raullaasner**
Clarify that it is in fact an API access token and not the user
password that is prompted when running singularity.

### CODE REVIEW

**Comment by wphuhn** [comment]
Does this work for you?  It's not working with me, which I presume is because I'm building the Singularity container as root, whereas my GitLab API key is tied to the SSH key on my local personal account.

**Comment by raullaasner** [comment]
I ran it as a normal user in VirtualBox, which has no information about me or my SSH key. Specifically, if I use my normal password I get this message:

```bash
user@user-VirtualBox:~/Downloads/FHI-aims_Singularity/gnu+mkl/ubuntu/18.04$ git clone https://aims-git.rz-berlin.mpg.de/aims/FHIaims.git src
Cloning into 'src'...
Username for 'https://aims-git.rz-berlin.mpg.de': raul_l
Password for 'https://raul_l@aims-git.rz-berlin.mpg.de': 
remote: HTTP Basic: Access denied
remote: You must use a personal access token with 'api' scope for Git over HTTP.
remote: You can generate one at https://aims-git.rz-berlin.mpg.de/profile/personal_access_tokens
fatal: Authentication failed for 'https://aims-git.rz-berlin.mpg.de/aims/FHIaims.git/'
```

After I did as instructed in the error message it worked. I'm guessing this is a typical scenario for installing the Singularity container and so others might see a similar error message.

**Comment by raullaasner** [comment]
So maybe include the original text *and* the proposed change? Something like *if* the user encounters an error message like above, then follow these instructions.

**Comment by wphuhn** [comment]
OK, merged in.

**Pull request merged**
